### ISSUE TITLE
FANN 2.2 library

### ISSUE THREAD

**Issue by youlweb** [bukka/php-fann#14]
Thank you for creating such a great wrapper for this awesome library. I installed it, and everything worked fine, until I tried to use `fann_create_train_from_callback`, which was missing.
The FANN library version from ubuntu's repo is 2.1, which seems to be missing a few features. I installed FANN 2.2 manually without a glitch, but php-fann doesn't work anymore. I tried to re-install php-fann through pecl, but got the following error:
`checking for fann support... yes, shared
checking for libfann headers in default path... found in /usr/local
checking for fann_set_user_data in -lfann... no
configure: error: wrong libfann version (you need at least version 2.1) or lib not found`
Then I tried to install it manually, only to get the same error.
Any help appreciated.

**Comment by bartwell** [comment]
I am also faced with a problem 'wrong libfann version' but on Mac OS. After some research I just removed libfann version checkout in config.m4:

```
  PHP_CHECK_LIBRARY($LIBNAME,$LIBSYMBOL,
  [
    AC_CHECK_LIB($LIBNAME,[fann_copy],[ AC_DEFINE(HAVE_FANN_2_2,1,[Fann library version 2.2]) ],[],[])
    AC_DEFINE(HAVE_FANN,1,[Fann library found])
  ],[
    AC_MSG_ERROR([wrong libfann version (you need at least version 2.1) or lib not found])
  ],[
  ])
```

There was also a problem `Cannot find libfann headers`, so I changed SEARCH_PATH variable to add a path:
```
SEARCH_PATH="/usr/local /usr /local /opt /opt/homebrew/Cellar/fann/2.2.0"
```

Then I got a an error `'phpc/phpc.h' file not found` and I just downloaded [php.c](https://raw.githubusercontent.com/bukka/phpc/master/phpc.h) and put it in phpc directory.

It is works well now.
