### ISSUE TITLE
php-pecl-fann-1.0.7/NTS/fann.c:1185L bad if test ?

### ISSUE THREAD

**Issue by dcb314** [bukka/php-fann#15]
php-pecl-fann-1.0.7/NTS/fann.c:1185:51: warning: comparison of constant '3' with boolean expression is always true [-Wbool-compare]

#define PHP_FANN_PATH_OK(_retval) Z_TYPE(_retval) != IS_BOOL || !Z_BVAL(_retval)

Suggest add () to make meaning clear and then () around the whole thing, because
users of this macro do things like this:

       if (!PHP_FANN_PATH_OK(retval)) {

**Comment by bukka** [comment]
Thanks for the report. The check of the dir perm was completely incorrect. Fixed now...
