### ISSUE TITLE
Fatal error: not identified sfunction

### ISSUE THREAD

**Issue by saturn2016** [bukka/php-fann#18]
I could install fann in ubunto 12.04 without problems.
I run the example: php simple_train.php and got an error
 in both command line and in browser as http://localhost/simple_train.php

*in command line the fatal error related to a not identified neural function is reported.
*in browser does not return anything. 

please advice thank you.
Saturn

ps: i installed xampp in windows too but the installation of library there seems much more complicated.

**Comment by bukka** [comment]
Can you copy and paste an exact error that you get from command line? Could you also check phpinfo if there is a fann section and what it says.

**Comment by bukka** [comment]
I'm closing this as not enough informations have been provided. Please comment on this if you still experience the problem and you are able to provide the requested informations. I can re-open it in that case...
