### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by lstrojny** [bukka/php-fann#19]
php-fann is not yet compatible with PHP 7

**Comment by bukka** [comment]
Yeah I plan to port it. I have created a next branch ( https://github.com/bukka/php-fann/tree/next ) a month ago and had to add support for resources to https://github.com/bukka/phpc that will be used as a compat layer. I'll have to add few more thing to phpc and then start porting ;). I will close this once it's done.

**Comment by lstrojny** [comment]
Cool, thank you!

**Comment by alrik11es** [comment]
:+1:

**Comment by bukka** [comment]
Stable version 1.1.0 with PHP 7 support has just been released ;)

**Comment by lstrojny** [comment]
Thank you! :+1:
