### ISSUE TITLE
configure: error: Cannot find libfann headers

### ISSUE THREAD

**Issue by xandrani** [bukka/php-fann#20]
fann.h doesn't seem to exist so the ./configure script gives the error:

"configure: error: Cannot find libfann headers"

This is on OSX 10.9.5

**Comment by bukka** [comment]
you need to install libfann first. You can install either from source

https://github.com/libfann/fann#from-source

or from some the distro repository (e.g. RHEL based or Debian based)...

**Comment by bukka** [comment]
Ah just see that you are on the Mac so you might also try Homebrew. It should be in homebrew/science so something like that should do:
```
$ brew tap homebrew/science
$ brew install fann
```

**Comment by xandrani** [comment]
Thanks Jakub

Really appreciate that.

Mike :-)

**Comment by ajthenewguy** [comment]
MacOS 10.15.7 (Catalina)
```
$ php -v
PHP 7.4.6 (cli) (built: May 14 2020 10:38:36) ( NTS )
```

`$ brew tap brewsci/science`
According to: https://stackoverflow.com/a/63779219/674033

Attempting to install the library yields:
```
$ brew install fann
==> Installing fann from brewsci/science
==> Downloading https://downloads.sourceforge.net/project/fann/fann/2.2.0/FANN-2.2.0-Source.tar.gz
Already downloaded: /Users/allen/Library/Caches/Homebrew/downloads/d3737f231368ec6a6a8751cc1d577dd8022ddc7ec6adb46fa4200b4129cb3b45--FANN-2.2.0-Source.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `universal?' for #<BuildOptions:0x00007f90358e2d68>
```

**Comment by anton-vlasenko** [comment]
I've resolved the error by running the following commands:

```bash
sudo ln -s /opt/homebrew/Cellar/fann/2.2.0/include /opt/include
sudo ln -s /opt/homebrew/Cellar/fann/2.2.0/lib/*.dylib /usr/local/lib/
```

These commands make the dynamic libraries and header files available for the PECL install script.

*Environment: Apple silicon, Homebrew, macOS 14.7*
