### ISSUE TITLE
PHP Fatal error:  Call to undefined function fann_create_standard()

### ISSUE THREAD

**Issue by ychoucha** [bukka/php-fann#21]
Hello i trying it on ubuntu serveur 14.04 : 

So first i install the libfan-dev library : 

```sudo apt-get install libfann-dev```

after that i git the libfan php : 

```git clone https://github.com/bukka/php-fann.git
```

after that i lunch the training : 

```
user1[/var/www/html_prod/php-fann/examples] > php simple_train.php
PHP Fatal error:  Call to undefined function fann_create_standard() in /var/www/html_prod/php-fann/examples/simple_train.php on line 11
```

what is wrong please ?

**Comment by ychoucha** [comment]
well if i lunch this : 

```
 [~/php-fann] > php fann.php
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/ayoub/php-fann/fann.php on line 5
Functions available in the test extension:
PHP Warning:  Invalid argument supplied for foreach() in /home/ayoub/php-fann/fann.php on line 10

Module fann is not compiled into PHP

```

of cours i compile it :

**Comment by bukka** [comment]
These messages say that extension is not enabled (at least not in php.ini and doesn't even look you compiled it properly). Have you followed exactly these steps:

https://github.com/bukka/php-fann#manual-installation

**Comment by bukka** [comment]
Closing as this doesn't seem like extension issue
