### ISSUE TITLE
fann_create_standard_array with 0-neuron layer

### ISSUE THREAD

**Issue by dseguy** [bukka/php-fann#25]
Calling fann_create_standard_array() with some layers with 0 neurons, generate a Floating point exception: 8 and a crash.

Yes, it is a bad idea to have an empty layer in the NN though php-fann should fail nicely.

**Comment by bukka** [comment]
I just tried the following script:

```php
$num_layers = 2;
$num_neurons1 = 0;
$num_neurons2 = 2;

var_dump( fann_create_standard_array( $num_layers, array( $num_neurons1, $num_neurons2 ) ) );
```

However that doesn't crash. Please could you provide a script that crashes?

**Comment by bukka** [comment]
Closing as there is no feedback and it can't be recreated...

@dseguy Happy to re-open if you post the code that is causing it.
