### ISSUE TITLE
Windows DLL Issues

### ISSUE THREAD

**Issue by geekgirljoy** [bukka/php-fann#32]
Hi @bukka,

When trying to use the [FANN Windows DLLs] (https://pecl.php.net/package/fann) I have encountered the following errors:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\fanndouble.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\fanndouble.dll' - The specified module could not be found.
 in Unknown on line 0
```

**Note that extension=php_fann.dll & extension=fanndouble.dll have been added to the PHP.ini file.**

Development environment is:
Windows 10 build 14393 (Windows 10) i586
XAMPP Control Panel v3.2.2
Apache 2.4
PEAR Version: 1.10.1 
PHP Version: 7.1.1
Zend Engine Version: 3.1.0

Is it possible to rebuild the dll files or advise how I might do so?

Thank you,
Joy

**Comment by EagleErwin** [comment]
As I mentioned earlier in #27, did you check the architecture of your PHP environment with the one of your DLL?

> The only thing I can think about, is that you are using the x86 DLL on a x64 PHP version, or vice versa.
You check your phpinfo(), make sure the DLL matches the architecture that is shown at "PROCESSOR_ARCHITECTURE" at the "Environment" section.

**Comment by geekgirljoy** [comment]
Hi @EagleErwin, yes I confirmed that I am using the correct DLL for my architecture but to be safe I tried both just in case. Please advise further if possible. Thank  you!

**Comment by EagleErwin** [comment]
Some other things that might help:
- Make sure that the thread safety matches your PHP environment. On the `phpinfo()` page, check the value for "Thread Safety". If it says "Enabled", you should use the TS version of the DLL. Otherwise, you should use the NTS version.
- In your post you mention `fanndouble.dll`, but I think you mean `doublefann.dll`. In any case, this DLL should **NOT** be in your `php.ini` configuration, it is only a dependency for `php_fann.dll`. For this dependency to be found, make sure it is located in a folder that is on your PATH (probably the directory your `php.exe` is located).

With these things not correctly set-up, I was able to reproduce this error in my environment:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\fanndouble.dll' - The specified module could not be found.
 in Unknown on line 0
```

However, I have never seen the message `%1 is not a valid Win32 application.`, so if your problem is not solved with the instructions above, I can try to find a cause for that message.

**Comment by geekgirljoy** [comment]
Hi @EagleErwin,

I truly appreciate your assistance with this as I am pulling my hair out on this one.  :-P

Thanks for pointing out about the DLL's I resorted to testing with the libFANN C++ DLL to see if that would work however that was unhelpful.

I just confirmed that I am using a Thread Safe installation with the correct DLLs downloaded from PECL, downloaded again to be sure.

Additionally I do have Visual Studio 2015 installed. 

I am still getting this error:

```

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - The specified module could not be found.
 in Unknown on line 0

```

I appreciate any further thoughts you may have on resolving this issue. 

Thank you,
~Joy

**Comment by geekgirljoy** [comment]
@bukka @EagleErwin  I have resolved this issue.

It seems that doublefann.dll is not supposed to reside in the ext folder with php_fann.dll

At least with XAMPP it seems that doublefann.dll should be in the root of the PHP folder.

 So here is what the structure should be:

```
[C:\xampp\php\]
             ├──   php.exe
             ├──   doublefann.dll
             └── [ext]
                     └── php_fann.dll
```

Seemingly this would be the case on all installations? If so I would be happy to update the readme and so a PR.

Thanks again for all your assistance with this!

~Joy

**Comment by EagleErwin** [comment]
As I mentioned with the second bullet in my previous post, the doublefann.dll should be in a folder that is in your PATH environment. Quite often, this will be the same directory as your php.exe executable (so you can use php on the command line in every working directory), but Windows\System32\ would work as well.

I have not seen it in any installation manual or readme file, so I think it is a nice addition.

**Comment by bukka** [comment]
@geekgirljoy Glad it's been resolved!

@EagleErwin Thanks for helping with this issue.

About the manual, I don't know much about win setup but if you are able to create a PR for the Readme about this, I will be happy to merge it ;)

**Comment by didlie** [comment]
I followed the same procedure, installed the doublefann.dll in xampp/php and put php_fann.dll in the ext dir and referenced it in php.ini with extension=php_fann.dll .... still doesnt work. I check the versions. My version of php is 7.1 TS x86 architecture, but I am running on a 64bit Windows 10. The version of php_fann.dll is from the php_fann-1.1.1-7.1-ts-vc14-x86.zip download.... still doesn't work. The runtime error is "Fatal error: Uncaught Error: Call to undefined function fann_create_standard() in C:\xampp2\htdocs\domtest\test_fann.php:13 Stack trace: #0 C:\xampp2\htdocs\domtest\index.php(8): require_once() #1 {main} thrown in C:\xampp2\htdocs\domtest\test_fann.php on line 13"

**Comment by cleoni** [comment]
The same happens using PHP on a XAMPP install on Win10. my php is 7.0 TS x86 and while the extension is seen using php from the command line, it won't load inside the webserver, and after startup the php_errors log reports:

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - The specified module could not be found.
 in Unknown on line 0

I have got the php_fann.dll extension in php/ext while doublefann.dll has been copied both inside c:\xampp\php and c:\windows\system32
