### ISSUE TITLE
Does not compile with PHP 8.1

### ISSUE THREAD

**Issue by dougherty-dev** [bukka/php-fann#44]
FANN does not work with PHP 8.1. (Ubuntu 20.04)

/tmp/pear/temp/fann/fann.c:1192:12: warning: passing argument 1 of ‘php_stat’ from incompatible pointer type [-Wincompatible-pointer-types]
 1192 |   php_stat(path, (php_stat_len) path_len, FS_IS_R, &retval TSRMLS_CC);

In file included from /tmp/pear/temp/fann/fann.c:28:
/usr/include/php/20210902/ext/standard/php_filestat.h:44:35: note: expected ‘zend_string *’ {aka ‘struct _zend_string *’} but argument is of type ‘char *’
   44 | PHPAPI void php_stat(zend_string *filename, int type, zval *return_value);

etc.

ERROR: `make' failed

===

EDIT: git-clone and manual install works fine, but not PECL installation.

**Comment by bukka** [comment]
Just release 1.2.0RC2 which fixes the reported issue.
